apiVersion: apps/v1
kind: Deployment
metadata:
  name: cf-tunnel
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: cf-tunnel
  template:
    metadata:
      labels:
        app: cf-tunnel
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args:
        - tunnel
        - --no-autoupdate
        - --loglevel
        - debug
        - run
        - --protocol
        - auto
        env:
        - name: TUNNEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: cf-tunnel-env
              key: CF_TUNNEL_TOKEN
        ports:
        - containerPort: 2000
          name: metrics
