apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http
      name: http
  selector:
    app: keycloak
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-discovery
  namespace: keycloak
  labels:
    app: keycloak
spec:
  selector:
    app: keycloak
  clusterIP: None
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: keycloak
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "keycloak-role"
        vault.hashicorp.com/auth-config-audience: "https://kubernetes.default.svc.cluster.local"
        vault.hashicorp.com/agent-inject-secret-credentials: "kv/data/keycloak"
        vault.hashicorp.com/agent-inject-template-credentials: |
          {{- with secret "kv/data/keycloak" -}}
          export POSTGRES_USER="{{ .Data.data.user }}"
          export POSTGRES_PASSWORD="{{ .Data.data.password }}"
          {{- end -}}
    spec:
      serviceAccountName: keycloak-sa
      containers:
        - name: postgres
          image: mirror.gcr.io/postgres:17
          command: ["/bin/sh", "-c"]
          args:
            - |
              if [ -f /vault/secrets/credentials ]; then
                source /vault/secrets/credentials
              fi
              docker-entrypoint.sh postgres
          env:
            - name: POSTGRES_DB
              value: "keycloak"
          ports:
            - name: postgres
              containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: keycloak
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP