apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: github-token-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-ceph-block

