apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
spec:
  selector:
      matchLabels:
        app: keycloak
  template:
    metadata:
      labels:
          app: keycloak
      annotations:
        # Vault Agent を有効化
        vault.hashicorp.com/agent-inject: "true"
        # 使用するロール名
        vault.hashicorp.com/role: "keycloak-role"
        # 認証時の audience (先ほど確認したもの)
        vault.hashicorp.com/auth-config-audience: "https://kubernetes.default.svc.cluster.local"
        # テンプレート：Vaultの値をどのファイルに書き出すか定義
        vault.hashicorp.com/agent-inject-secret-credentials: "kv/data/keycloak"
        # 書き出す内容のフォーマット（シェル変数形式）
        vault.hashicorp.com/agent-inject-template-credentials: |
          {{- with secret "kv/data/keycloak" -}}
          export KC_DB_PASSWORD="{{ .Data.data.password }}"
          export KC_DB_USERNAME="{{ .Data.data.user }}"
          export KC_BOOTSTRAP_ADMIN_PASSWORD="{{ .Data.data.password }}"
          export KC_BOOTSTRAP_ADMIN_USERNAME="{{ .Data.data.user }}"
          {{- end -}}
    spec:
      serviceAccountName: keycloak-sa # 作成したSAを指定
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.5.5
          command: ["/bin/sh", "-c"]
          args:
            - |
              if [ -f /vault/secrets/credentials ]; then
                source /vault/secrets/credentials
              fi
              /opt/keycloak/bin/kc.sh start
          env:
            - name: KC_PROXY_HEADERS
              value: "xforwarded"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KC_CACHE
              value: "ispn"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KC_CACHE_EMBEDDED_NETWORK_BIND_ADDRESS
              value: '$(POD_IP)'
            - name: KC_DB_URL_DATABASE
              value: 'keycloak'
            - name: KC_DB_URL_HOST
              value: 'postgres'
            - name: KC_DB
              value: 'postgres'
          ports:
            - name: http
              containerPort: 8080