persistence:
  enabled: true
  existingClaim: jenkins-home

serviceAccount:
  create: false
  name: jenkins-controller

controller:
  image:
    registry: docker.io
    repository: jenkins/jenkins
    tag: lts-jdk17
    pullPolicy: IfNotPresent

  serviceType: ClusterIP

  persistence:
    enabled: true
    existingClaim: jenkins-jobs

  testEnabled: false

  serviceAccountName: jenkins-controller
  serviceAccount:
    create: false
    name: jenkins-controller
  
  podAnnotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "jenkins-agent"

    vault.hashicorp.com/agent-inject-secret-jenkins_username: "kv/data/jenkins"
    vault.hashicorp.com/agent-inject-template-jenkins_username: |
      {{ "{{" }}- with secret "kv/data/jenkins" -{{ "}}" }}
      {{ "{{" }} .Data.data.jenkins_username {{ "}}" }}
      {{ "{{" }}- end -{{ "}}" }}

    vault.hashicorp.com/agent-inject-secret-jenkins_password: "kv/data/jenkins"
    vault.hashicorp.com/agent-inject-template-jenkins_password: |
      {{ "{{" }}- with secret "kv/data/jenkins" -{{ "}}" }}
      {{ "{{" }} .Data.data.jenkins_password {{ "}}" }}
      {{ "{{" }}- end -{{ "}}" }}

    vault.hashicorp.com/agent-inject-secret-github_token: "kv/data/github"
    vault.hashicorp.com/agent-inject-template-github_token: |
      {{ "{{" }}- with secret "kv/data/github" -{{ "}}" }}
      {{ "{{" }} .Data.data.token {{ "}}" }}
      {{ "{{" }}- end -{{ "}}" }}
    
    vault.hashicorp.com/agent-inject-secret-private_key: "kv/data/jenkins"
    vault.hashicorp.com/agent-inject-template-private_key: |
      {{ "{{" }}- with secret "kv/data/jenkins" -{{ "}}" }}
      {{ "{{" }} .Data.data.private_key {{ "}}" }}
      {{ "{{" }}- end -{{ "}}" }}

    vault.hashicorp.com/agent-inject-secret-public_key: "kv/data/jenkins"
    vault.hashicorp.com/agent-inject-template-public_key: |
      {{ "{{" }}- with secret "kv/data/jenkins" -{{ "}}" }}
      {{ "{{" }} .Data.data.public_key {{ "}}" }}
      {{ "{{" }}- end -{{ "}}" }}

    vault.hashicorp.com/agent-inject-secret-discord_webhook_url: "kv/data/jenkins"
    vault.hashicorp.com/agent-inject-template-discord_webhook_url: |
      {{ "{{" }}- with secret "kv/data/jenkins" -{{ "}}" }}
      {{ "{{" }} .Data.data.discord_webhook_url {{ "}}" }}
      {{ "{{" }}- end -{{ "}}" }}

agent:
  enabled: true
  image:
    registry: docker.io
    repository: jenkins/inbound-agent
    tag: latest

# helm upgrade --install jenkins jenkinsci/jenkins --namespace jenkins --create-namespace -f jenkins-values.yaml
