apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-container
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: nginx
            topologyKey: kubernetes.io/hostname
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        - containerPort: 40000
        - containerPort: 40001
        - containerPort: 40002
        - containerPort: 40003
        - containerPort: 40004
        - containerPort: 40005
        volumeMounts:
          - name: nginx-conf
            mountPath: /etc/nginx/conf.d
            readOnly: true
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - name: mkeys-php
      protocol: TCP
      port: 40000
      targetPort: 40000

    - name: nas
      protocol: TCP
      port: 40001
      targetPort: 40001

    - name: nas-console
      protocol: TCP
      port: 40002
      targetPort: 40002

    - name: proxmox-console
      protocol: TCP
      port: 40003
      targetPort: 40003

    - name: jenkins 
      protocol: TCP
      port: 40004
      targetPort: 40004

    - name: jenkins-hook 
      protocol: TCP
      port: 40005
      targetPort: 40005

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  param.conf: |
    # /etc/nginx/conf.d/params.conf

    proxy_buffers 4 256k;
    proxy_buffer_size 128k;
    proxy_busy_buffers_size 256k;
    proxy_temp_file_write_size 512k;
    
    proxy_ssl_verify off;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    
    proxy_read_timeout 3600;
    proxy_send_timeout 3600;

  web.conf: |
    
    # /etc/nginx/conf.d/web.conf
    server {
      listen 0.0.0.0:40000;
      listen [::]:40000;
      server_name www.mkeys.blog;
      proxy_set_header Host www.mkeys.blog;

      resolver 10.96.0.10 valid=10s ipv6=off;

      location / {
        set $upstream "mkeys-php.mkeys.svc.cluster.local";
        proxy_pass http://$upstream;
        include /etc/nginx/conf.d/param.conf;
      }
    }

    server {
      listen 0.0.0.0:40004;
      listen [::]:40004;
      server_name jenkins.newvia.net;
      proxy_set_header Host jenkins.newvia.net;
      
      resolver 10.96.0.10 valid=10s ipv6=off;

      location / {
        set $upstream "jenkins.jenkins.svc.cluster.local:8080";
        proxy_pass http://$upstream;
        include /etc/nginx/conf.d/param.conf;
      }
    }
    

    server {
      listen 0.0.0.0:40005;
      listen [::]:40005;
      server_name jenkins-hook.newvia.net;
      proxy_set_header Host jenkins-hook.newvia.net;
      
      resolver 10.96.0.10 valid=10s ipv6=off;

      location / {
        set $upstream "jenkins.jenkins.svc.cluster.local:8080";
        proxy_pass http://$upstream;
        # proxy_pass http://172.32.0.8:8080;
        include /etc/nginx/conf.d/param.conf;
      }
    }

    server {
      listen 0.0.0.0:40002;
      listen [::]:40002;
      server_name nas-console.newvia.net;
      proxy_set_header Host nas-console.newvia.net;
      
      resolver 10.96.0.10 valid=10s ipv6=off;

      location / {
        proxy_pass http://172.31.0.5;
        include /etc/nginx/conf.d/param.conf;
      }
    }

    server {
      listen 0.0.0.0:40001;
      listen [::]:40001;
      server_name nas.newvia.net;
      proxy_set_header Host nas.newvia.net;
      
      resolver 10.96.0.10 valid=10s ipv6=off;

      location / {
        proxy_pass http://172.31.0.5:30027;
        include /etc/nginx/conf.d/param.conf;
      }
      client_max_body_size 0;
    }

    server {
      listen 0.0.0.0:40003;
      listen [::]:40003;
      server_name proxmox-console.newvia.net;
      proxy_set_header Host 172.32.0.101;

      location / {
        proxy_pass https://172.32.0.101:8006;
        include /etc/nginx/conf.d/param.conf;
      }
    }
